- httomo/data/hdf/loaders.py
- httomo/methods_database/packages/httomo.yaml
- httomo/methods_database/packages/httomolib.yaml
- httomo/methods_database/packages/tomopy.yaml
- httomo/methods_database/query.py
- httomo/task_runner.py
- httomo/utils.py
- wrappers/httomolib/misc.py
- wrappers/httomolib/prep.py
- wrappers/httomolib/recon.py
- wrappers/tomopy/misc.py
- wrappers/tomopy/prep.py
- wrappers/tomopy/recon.py
This PR is intended to address #61.
The main change is to replace the `@pattern` decorator (which was used on method functions to associate patterns to the function objects), with storing pattern information in separate YAML files and fetching this information in the runner.
> Move pattern information to separate YAML files

- httomo/task_runner.py
- httomo/wrappers_class.py
This adds a timing output for the execution tasks and fixes an issue with selecting the right GPU. The `with` statement that was there before seems to reset the selected GPU to 0 after, so had to revert to the `use()` method of the device.
> Adds timing + fixes GPU selection

- httomo/data/hdf/_utils/reslice.py
- httomo/data/mpiutil.py
- tests/test_mpiutil.py
- tests/test_reslice.py
This fixes the MPI problem with reslice operations if the chunks are larger than `INT_MAX` elements (roughly 2 billion). This is a well-known issue with MPI, as all size and offset parameters accept the C type `int`, which is 32bit on most systems. A common way to address this is to create a new custom data type that is composed of multiple elementary elements joined together, and then a smaller number of elements of this new type can be sent. Note that this does not change the data itself - it's merely a different way to tell MPI what to transfer.
Further to this, it was discovered that the default `mpi4py` way to transfer Python objects is to pickle them first, then transfer, and than unpickle. With numpy arrays that we have, we can actually work directly with the raw data buffers if we …
> Fix MPI size limitation for large reslice operations

- httomo/task_runner.py
- httomo/wrappers_class.py
- tests/test_pipeline.py
Follows discussion in #55 but actually keeping most of things as they are. 
The main changes are: 
- dictionaries have `dict` in front of them and renamed as: `dict_datasets_pipeline, dict_params_method, dict_httomo_params`. I don't think we need something more granular than this at this point. 
- Function objects renamed to  `func_method, func_wrapper`. One assciated with the actual method and one with the wrapper
- In the wrapper class there were incorrect descriptions for `params` dictionary, now fixed with the less ambiguous name: `dict_params_method`
> more consistent naming for dictionaries and functions #55

- httomo/yaml_checker.py
- samples/pipeline_template_examples/testing/incorrect_method.yaml
- samples/pipeline_template_examples/testing/more_than_one_method.yaml
- samples/pipeline_template_examples/testing/wrong_indentation_pipeline.yaml
- tests/conftest.py
- tests/test_yaml_checker.py
> Add basic YAML checker

- httomo/cli.py
- tests/test_pipeline.py
This is a fairly basic change so there's not much to say. One comment is that, with Savu runs, there is a separation of output data from logfiles by putting the logfiles and copied process list file into a subdirectory called `run_log/`, like so (I've ignored some other irrelevant subdirectories in the output below to keep it tidy):
```
[twi18192@pc0074 20221119164836_119497]$ tree -I 'checkpoint|stats'
.
├── 119497_processed.nxs
├── cor_broadcast_p2_vo_centering.h5
├── cor_preview_p2_vo_centering.h5
├── run_log
│   ├── citations.txt
│   ├── run_command.txt
│   ├── savu_benchmark.savu
│   └── user.log
├── tomo_p1_dark_flat_field_correction.h5
├── tomo_p3_remove_all_rings.h5
└── tomo_p4_astra_recon_gpu.h5
1 directory, 10 files
```
So, maybe that's something we would want to do in the …
> Copy YAML pipeline file to output dir prior to run

- MANIFEST.in
- pyproject.toml
See the commit message 69a66f1 for more info if interested, but the TL;DR is that the installation was incomplete, due to not copying some YAML files that are necessary for HTTomo to be able to run pipelines.
It was only detectable via tests by running a test that ran a pipeline (ie, what we've marked as "GPU tests") after a fresh installation of HTTomo, and we only run CPU tests through CI so this failed to get detected in the Github actions.
> Improve package and YAML file discovery in `pyproject.toml`

- httomo/cli.py
- tests/test_cli.py
Not much explanation needed I guess, pretty simple.
Fixes #131.
> Add CLI flag for naming the output dir created by HTTomo

- tests/test_pipeline.py
We saw some potential ambiguity in the ordering of files when running some tests (due to different workstations producing failing or passing tests), such as in https://github.com/DiamondLightSource/httomo/blob/memory/tests/test_pipeline.py#L444-L455.
In this PR, the tests which depended on using indices to determine which files to load have been changed to specify a substring of the desired filename instead, in an attempt to avoid ambiguity.
> Specify tiff and h5 files in output dir to load in tests

- httomo/postrun.py
- httomo/prerun.py
- samples/pipeline_template_examples/DLS/02_i12_360scan_pipeline.yaml
- tests/conftest.py
- tests/test_load.py
- tests/test_loader.py
- tests/test_pipeline.py
deal with #150 
Adding 360 degrees scan sample data, fixes the pipeline and adds the test.
also adds a fix for the post_run with intermediate data saving.
> 360 scan pipeline (GPU), data, test

- httomo/common.py
- httomo/prerun.py
- httomo/task_runner.py
- httomo/wrappers_class.py
- tests/test_task_runner.py
This has moved the reslice operation from the `run_method()` function to the sections-loop.
Note that the execution of methods is still in `run_method()`, so the current state is the following:
- reslices are being done within the sections-loop
- the sections-loop is not executing any methods yet
- _after_ the sections-loop finishes, methods are executed via a loop calling `run_method()`
Therefore, the reslices are **not** happening in the correct places in the execution of the pipeline. Once the execution of the methods has been moved to the methods-loop (the innermost loop within the sections-loop), this should be resolved.
> Move reslice to section loop

- docs/source/reference/loaders.rst
- httomo/data/hdf/_utils/load.py
- httomo/data/hdf/loaders.py
- samples/pipeline_template_examples/DLS/04_i12_ignore_darks_flats.yaml
- tests/conftest.py
- tests/test_loader.py
- tests/test_pipeline.py
Fixes #157
Specifying individual indices of darks/flats is supported, as well as specifying a range of indices via start and stop values.
TODO list:
- ~OPTIONAL: Move the parameters `ignore_darks` and `ignore_flats` to be within the existing `darks` and `flats` parameters~
> Add loader params for ignoring darks/flats

- httomo/cli.py
- httomo/common.py
- httomo/data/hdf/_utils/reslice.py
- httomo/pipeline_reader.py
- httomo/preprocess.py
- httomo/task_runner.py
- httomo/wrappers_class.py
- httomo/yaml_checker.py
- httomo/yaml_loader.py
- httomo/yaml_utils.py
- samples/loader_configs/diad.yaml
- samples/loader_configs/standard_tomo.yaml
- samples/pipeline_template_examples/02_basic_cpu_pipeline_tomo_standard.yaml
- samples/pipeline_template_examples/03_basic_gpu_pipeline_tomo_standard.yaml
- samples/pipeline_template_examples/parameter_sweeps/02_median_filter_kernel_sweep.yaml
- samples/pipeline_template_examples/testing/empty_loader_stage.yaml
- samples/pipeline_template_examples/testing/incorrect_method.yaml
- samples/pipeline_template_examples/testing/incorrect_path.yaml
- samples/pipeline_template_examples/testing/invalid_loader_stage.yaml
- samples/pipeline_template_examples/testing/missing_loader_stage.yaml
- samples/pipeline_template_examples/testing/more_than_one_method.yaml
- samples/pipeline_template_examples/testing/required_param.yaml
- samples/pipeline_template_examples/testing/testing_pipeline.yaml
- tests/conftest.py
- tests/test_loader.py
- tests/test_pipeline.py
- tests/test_task_runner.py
- tests/test_yaml_checker.py
Main changes:
- add loader and pre-processing stages to pipeline YAML files via multiple "documents" within the YAML file
- enable dezinging (optional) and centering (mandatory) as part of the pre-processing stage
- try out defining a class for reading pipeline YAML files, as a test candidate for some refactoring
- refactor `test_yaml_checker.py` such that each individual check can be tested in isolation
> Add pre-processing stage to pipeline

- httomo/data/dataset_store.py
- httomo/runner/dataset_store_interfaces.py
- tests/data/test_dataset_store.py
This adapts data store to do the following:
- when calling `make_reader`, it marks the writer as read-only and does not allow further blocks to be written
- it closes the hdf5 file when passing to the reader, and the reader re-opens it. This ensures that data is properly flushed to disk
- it registers the class finalisers with `weakref`, making sure it's always called with garbage collection
Further, it transforms to American spelling of `finalize`, as is the common convention.
> Properly closes and delete file in all cases

- tests/test_loader.py
- tests/test_pipeline.py
This makes sure that all tests are passing in `feature/transparent-file-store`, to have a clean base for other branches.
> Fix tests in transparent file store branch

- httomo/runner/loader.py
- tests/conftest.py
- tests/runner/test_loader.py
An assortment of small improvements:
- reduce duplicate boilerplate code in loader tests for creating loader object
- modify relative paths to work regardless of current working directory when executing loader tests
- store a file handle to the hdf5 file on the loader so then the file doesn't need to be opened more than once
- implement the `finalize()` method on `StandardTomoLoader` to make it satisfy to the `DataSetSource` interface once more
> Refactor `StandardTomoLoader` and associated tests

- httomo/data/dataset_store.py
- httomo/method_wrappers/rotation.py
- httomo/runner/dataset.py
- httomo/runner/loader.py
- tests/runner/test_dataset.py
The issue was that the gathering of the single sinogram slice was using the shape of the global data _including_ darks/flats, rather than the shape of the data with the darks/flats _excluded_.
It was possible to fix by fiddling with the `shape` and `global_shape` properties of the data objects, but it should be considered a workaround rather than a proper fix, fiddling with these various properties feels fragile.
> Fix incorrect data shape used for single sino gather

- httomo/runner/dataset.py
- httomo/runner/loader.py
- tests/runner/test_loader.py
Provides a workaround to the following error during pipeline execution (for example, `test_run_diad_pipeline_gpu` exhibits the error):
```
File "/httomo/httomo/runner/dataset.py", line 163, in _set_data
self._global_index[dim] == 0
AssertionError: shape in slicing dim changed, which is not allowed
```
> Use `data_offset` rather than `global_index` in loader

- httomo/data/dataset_store.py
- httomo/method_wrappers/generic.py
- httomo/methods_database/packages/external/httomolibgpu/1.2/httomolibgpu.yaml
- httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/misc/corr.py
- httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/prep/normalize.py
- httomo/runner/dataset.py
- httomo/runner/dataset_store_interfaces.py
- httomo/runner/loader.py
- httomo/runner/task_runner.py
- tests/method_wrappers/test_generic.py
- tests/runner/test_dataset.py
- tests/test_backends/test_httomolibgpu.py
- tests/test_method_query.py
This is a bugfix PR to fix the issue that memory / slices estimation did not take into account the size of the darks and flats, and the fact that they are transferred lazily to the GPU on demand. The fix works as follows.
- `DataSet` and classes inheriting from it have new properties `has_gpu_flats` and `has_gpu_darks`, which return a boolean depending if the lazy GPU transfer has already happend and the data is present in GPU memory already
- The memory estimation in `TaskRunner` first checks if any methods in the section need `darks` and `flats` as inputs, and if they are GPU methods
- If yes, it checks if the `darks` / `flats` have already been transferred to GPU (using `has_gpu_darks` and `has_gpu_flats`)
- If yes, the figure obtained for `available_memory_gpu` is left as it was
- If …
> Bugfix: Memory estimation including darks and flats

- tests/test_pipeline.py
This PR has various small fixes to the pipeline tests, mainly regarding the assertions being done on the log contents.
One other changes that's been done is that the pipeline test relying on ignoring darks/flats in the data has been commented out. This is because that functionality hasn't yet been added to the new loader, so it's a pointless test to have until the new loader gets that functionality.
> Fix pipeline tests

- templates/httomolib/1.2/httomolib.misc.images/save_to_images.yaml
- templates/yaml_templates_generator.py
Part of the work towards completing #246 
Goes together with the `asynchronous` parameter added to the image saver in https://github.com/DiamondLightSource/httomolib/pull/9
> Use alternative default val for image saver async param in template generator

- httomo/data/dataset_store.py
> Fix memory leak caused by reader/writer objects not being garbage collected during pipeline execution

- tests/runner/test_task_runner.py
Fixes `test_warns_with_multiple_reslices`.
Another situation where more data stores are created and written to is when methods with side outputs are in the pipeline. When the store is backed by an hdf5 file, this situation leads to multiple hdf5 files being written and slowing down the pipeline, effectively taking as much time as a file-based reslice, which motivated the changes to the logging in c3227df.
To cover this case, this PR also adds a test to check for when side outputs cause multiple data stores to be created.
> Fix reslice warning tests

- httomo/data/mpiutil.py
This provides a workaround to #274 , but whether it's a true fix or not is unknown.
> Workaround to RAM-based reslice segfault on SLURM nodes

- docs/source/howto/how_to_run/at_diamond.rst
- docs/source/howto/how_to_run/outside_diamond.rst
- docs/source/howto/run_httomo.rst
This updates the docs on the `run` command. And feedback for changes/improvements is welcome, there surely will be better ways to explain things than what first comes to my mind! :slightly_smiling_face: 
As discussed, the `check` command will be reintroduced later, so the docs mentioning `check` have been unchanged.
Note that this branch depends on `docs_update`, and should be merged into `gpuloop` after #277 is merged.
> Update "how to run httomo" docs

- httomo/yaml_checker.py
Fixes tests failing to run due to the import of a now removed module (was removed in #282)
> Remove import from non-existent `yaml_utils` module

- httomo/cli.py
- tests/test_cli.py
Essentially a duplicate of #137
Fixes #305 (see issue for details on how this relates to the DLS launcher script)
> Add CLI flag for naming the output dir created

- pyproject.toml
> Fix incorrect methods database YAML file globbing

- conda/environment.yml
- httomo/cli.py
- httomo/globals.py
- httomo/logger.py
> Add CLI flags to configure syslog handler

- httomo/utils.py
Fixes #301
Before change:
```
(/dls/science/users/twi18192/conda-envs/httomo) [twi18192@cs04r-sc-vserv-300 httomo (log-cupy-install-info)]$ python -m httomo_dls.launcher
CuPy is not installed
Usage: python -m httomo_dls.launcher [OPTIONS] IN_DATA_FILE YAML_CONFIG
OUT_DIR
Try 'python -m httomo_dls.launcher --help' for help.
Error: Missing argument 'IN_DATA_FILE'.
```
After change:
```
(/dls/science/users/twi18192/conda-envs/httomo) [twi18192@cs04r-sc-vserv-300 httomo (log-cupy-install-info)]$ python -m httomo_dls.launcher
Usage: python -m httomo_dls.launcher [OPTIONS] IN_DATA_FILE YAML_CONFIG
OUT_DIR
Try 'python -m httomo_dls.launcher --help' for help.
Error: Missing argument 'IN_DATA_FILE'.
```
> Change cupy installation prints to debug logs

- httomo/cufft.py
Trimmed-down version of
https://github.com/lebedov/scikit-cuda/blob/3c1338c4ecfa218d664c73dc70746862785ae555/skcuda/cufft.py that exposes only the functions from the cuFFT API that are needed in httomo for FFT plan related memory estimation
> Add cuFFT API wrappers for plan estimation

- conda/recipe/conda_build_config.yaml
- conda/recipe/meta.yaml
Fixes #352
Depends on #347 being merged first
The generated package names look something like the following (fixing it for python 3.10, and httomo version v2.0.0rc1 for the example):
```
httomo-2.0.0rc1_openmpi_regular
httomo-2.0.0rc1_openmpi_external
```
"Regular" and "external" refer to the build strings of the `openmpi` package that the different httomo package builds are based on.
I chose these names as a starting point just to get the work done, but the names themselves can easily be changed, so opinions on better naming are certainly welcome :)
Assume that  the packages are uploaded to the httomo conda channel.
Installation of the package using the "external" openmpi build variant (for installation at DLS) would be done via:
```
mamba install -c https://conda.anaconda.org/httomo/ …
```
> Build conda packages for openmpi "external" and "regular" build variants

- httomo/method_wrappers/rotation.py
- httomo/methods_database/packages/external/httomolib/httomolib.yaml
- httomo/methods_database/packages/external/httomolibgpu/httomolibgpu.yaml
- httomo/methods_database/packages/external/tomopy/supporting_funcs/misc/corr.py
- httomo/methods_database/packages/external/tomopy/supporting_funcs/prep/stripe.py
- httomo/methods_database/packages/external/tomopy/tomopy.yaml
- httomo/methods_database/packages/httomo.yaml
- httomo/methods_database/query.py
- httomo/runner/methods_repository_interface.py
- httomo/utils.py
- tests/conftest.py
- tests/test_backends/test_tomopy.py
- tests/test_method_query.py
This adds support in the methods database to flag which are requiring padding. It also adds a new supporting function to calculate the padding values depending on the parameters, returning a tuple for the left and right pad values for each method.
The methods added so far are all the methods with the `3d` suffix from tomopy, nothing else yet. Please check if the padding calculation functions are actually correct for these, and check if some 3d methods might have been missed. But also note that it's easy to add more in future.
(It also fixes some pytest warnings that were flagged on my box)
> Padding methods support in DB

- pyproject.toml
These dependencies have been missing in the pyproject dependency specs. Code is not runnable without.
> Adds missing dependencies to pyproject.toml file

- httomo/block_interfaces.py
- httomo/runner/dataset.py
- httomo/sweep_runner/param_sweep_block.py
- tests/runner/test_dataset_block.py
A small PR which simply adds interfaces and capabilities to the `DataSetBlock` for padding. It works as follows:
- a `padding` parameter is added to the constructor, which is a tuple of 2 `int` values. It means the number of padded slices to the left and to the right. 
- `block_shape` is adapted to include the padding, i.e. a `(2, 3)` padded block with a core shape of `(10, 3, 4)` and slicing dim `0` means it will  have `block_shape=(15, 3, 4)`.  This includes the 5 padding slices.
- `chunk_shape` is adapted in the same way - the shape is the previous chunk shape + the padding
- `chunk_index` and `global_index` are the indices within the chunk data or global data, respectively, where the block starts, so this includes the padding as well. This means there can be negative indices as well - …
> Adds padding capability to blocks

- httomo/cli.py
- httomo/data/hdf/_utils/reslice.py
- httomo/data/mpiutil.py
- httomo/method_wrappers/generic.py
- httomo/monitors/__init__.py
- httomo/monitors/benchmark.py
- httomo/monitors/summary.py
- httomo/runner/gpu_utils.py
- httomo/runner/task_runner.py
- httomo/transform_layer.py
- httomo/utils.py
- tests/method_wrappers/test_generic.py
- tests/monitors/test_aggregate.py
- tests/monitors/test_benchmark.py
- tests/monitors/test_summary.py
- tests/runner/test_gpu_utils.py
- tests/runner/test_task_runner.py
- tests/test_mpiutil.py
- tests/test_transform_layer.py
Various small changes to how a communicator object is used by httomo objects:
- hardcoded communicator objects in constructor logic are now passed in as a constructor parameter
- method wrappers are verified to only use communicator passed into the constructor for method execution (global communicator usage is limited to getting the GPU ID for a process)
- modify custom `alltoall()` to have communicator passed-in, instead of hardcoding usage of `MPI.COMM_WORLD`
- remove global vars relating to MPI in `mpiutil.py`
- define communicator objects in CLI, and pass them to the runner objects
> Rearrange comm usage

- httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/recon/algorithm.py
- tests/test_backends/test_httomolibgpu.py
(please adjust target branch - unsure if this should go to `dev` instead)
This fixes the memory estimation for the FBP algorithm. Here is a step by step breakdown of what happens in FBP in terms of allocation:
1. a 1D R2C FFT plan is created and used for [this real-to-complex FFT](https://github.com/dkazanc/ToMoBAR/blob/master/tomobar/fourier.py#L50) -> [fftplan_size](https://github.com/team-gpu/httomo/blob/bugfix/fbp-memory-estimation/httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/recon/algorithm.py#L79)
2. This creates a [complex output array with half the width](https://github.com/team-gpu/httomo/blob/bugfix/fbp-memory-estimation/httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/recon/algorithm.py#L89)
3. [An array for the filter is …
> Fixes for memory estimations in the FBP algorithm

- httomo/block_interfaces.py
- httomo/data/dataset_store.py
- httomo/runner/dataset.py
- httomo/sweep_runner/param_sweep_block.py
- tests/data/test_dataset_store.py
- tests/runner/test_dataset_block.py
This PR adds support for padded data to the `DataSetStoreWriter` and `DataSetStoreReader` classes. In particular:
- writing blocks that include padding to the `DataSetStoreWriter` results on the padding slices to be dropped and only the core area to be written. 
- the `DataSetStoreWriter.make_reader` method gained a parameter for padding. The idea is that the task runner will create the reader this way for the next section, and it knows if that section needs padding and how much. 
- the `DataSetStoreReader` correctly handles padding, i.e.:
- the reader properties `chunk_shape` and `global_index` are adapted to include the padding
- when `read_block(start, length)` is called, it automatically generates a padded block. The parameters `start` and `length` are regarding the core area, but the …
> DataSetStore with padding support

- httomo/method_wrappers/generic.py
- httomo/runner/method_wrapper.py
- httomo/runner/task_runner.py
- tests/method_wrappers/test_generic.py
- tests/runner/test_task_runner.py
This adds a few functions that calculate padding for different objects:
- method for wrapper to calculate padding via supporting functions in methods database
- method for runner to calculate padding of a section
- standalone function for runner to calculate the chunk shape (including padding) for the next section
- this was made a standalone function instead of a method to make testing easier (needing to create a `TaskRunner` object simply to calculate different chunks shapes is overkill in my opinion, and parametrisation of the logic is much easier when not needing to generate different `Pipeline` objects to create a list of `Section` objects using a runner object)
> Add padding calculators functions to wrapper and runner

- httomo/data/dataset_store.py
- httomo/data/padding.py
- httomo/loaders/standard_tomo_loader.py
- tests/data/test_padding.py
- tests/loaders/test_standard_tomo_loader.py
Fixes #414
Main changes:
- `_extrapolate_*()` methods in data store reader have been extracted into a separate `padding.py` module for reuse by the loader
- enable `StandardTomoLoader` to load padded blocks (with or without previewing applied to the original data)
> Enable `StandardTomoLoader` to load padded blocks

- httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/recon/algorithm.py
- httomo/runner/dataset.py
- httomo/runner/task_runner.py
- tests/test_backends/test_httomolibgpu.py
This PR removes the reference to CuPy array inside `DataSetBlock` before cleaning up by the CuPy memory pool. This ensures no Python object refers to the underlying CuPy memory pointer, so the CuPy memory pool knows the memory pointer is not referenced by some Python objects, and the memory pool can be properly cleaned up.
A simple deleter of `data` attribute in `DataSetBlock` is implemented to help the deletion of the CuPy array. 
Together with [this fix in `httomolibgpu`](https://github.com/DiamondLightSource/httomolibgpu/pull/145), it solves the GPU memory leak issue.
> Ensure no Python objects pointed to CuPy array before cleaning its memory pool 

- docs/source/howto/httomo_features/parameter_sweeping.rst
- docs/source/pipelines/yaml.rst
- httomo/method_wrappers/generic.py
- httomo/runner/method_wrapper.py
- httomo/transform_layer.py
- httomo/yaml_checker.py
- tests/conftest.py
- tests/samples/pipeline_template_examples/parameter-sweep-cor.yaml
- tests/samples/pipeline_template_examples/parameter-sweep-paganin.yaml
- tests/samples/pipeline_template_examples/testing/imagesave_after_sweep.yaml
- tests/test_pipeline.py
- tests/test_transform_layer.py
- tests/test_yaml_checker.py
- tests/testing_utils.py
Fixes #418 
Auto insertion works after a `sweep` method added AND if the reconstruction method is present it would also add another `save_to_images` method after it. This is due to users usually want to assess the change in the reconstructed images and not in projections or sinograms. Because of this, even if there is only one `sweep` method is present, `save_to_images` substitutions can be two. 
Tests added to test this, and also two pipelines added as tests. 
Yaml checker also changed  to check if `save_to_images` present after `sweep` methods and prompts a user to remove them as they are unnecessary.
> A feature for Sweep to insert save_to_images methods automatically 

- httomo/runner/task_runner.py
Fixes #437 
Slightly hacky fix for #437 to deal with the fact that the conversion to float32 happens after the data gets loaded. We should   essentially ignore `source.dtype`.  I wrote more about it in #436, but may be a separate issue should exist to deal with this in future separately from the library changes.
> Fixing OOM issue

- httomo/loaders/standard_tomo_loader.py
- tests/loaders/test_standard_tomo_loader.py
> Remove padding from loader's chunk shape calculation

- httomo/loaders/standard_tomo_loader.py
- httomo/method_wrappers/generic.py
- httomo/method_wrappers/save_intermediate.py
- httomo/methods_database/packages/external/httomolibgpu/httomolibgpu.yaml
- httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/misc/corr.py
- httomo/methods_database/query.py
- httomo/runner/loader.py
- httomo/runner/task_runner.py
- httomo/sweep_runner/param_sweep_runner.py
- tests/method_wrappers/test_data_reducer.py
- tests/method_wrappers/test_dezinging.py
- tests/method_wrappers/test_generic.py
- tests/method_wrappers/test_images.py
- tests/method_wrappers/test_reconstruction.py
- tests/method_wrappers/test_rotation.py
- tests/method_wrappers/test_save_intermediate.py
- tests/method_wrappers/test_stats_calc.py
- tests/runner/test_task_runner.py
- tests/sweep_runner/test_param_sweep_runner.py
- tests/test_method_query.py
- tests/testing_utils.py
This enables the task runner to load and process padded blocks.
> Integrate padding into runner

- httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/prep/phase.py
> Improve paganin filter method's memory estimation

- httomo/transform_layer.py
- tests/samples/pipeline_template_examples/DLS/01_diad_pipeline_gpu.yaml
- tests/samples/pipeline_template_examples/pipeline_360deg_gpu2.yaml
- tests/samples/pipeline_template_examples/pipeline_cpu1.yaml
- tests/samples/pipeline_template_examples/pipeline_cpu2.yaml
- tests/samples/pipeline_template_examples/pipeline_cpu3.yaml
- tests/samples/pipeline_template_examples/pipeline_cpu4.yaml
- tests/samples/pipeline_template_examples/pipeline_gpu1.yaml
- tests/samples/pipeline_template_examples/testing/testing_pipeline.yaml
- tests/samples/python_templates/pipeline_cpu1.py
- tests/samples/python_templates/pipeline_cpu2.py
- tests/samples/python_templates/pipeline_cpu3.py
- tests/samples/python_templates/pipeline_gpu1.py
- tests/test_pipeline.py
- tests/test_transform_layer.py
- tests/test_ui_layer.py
These changes are needed on the httomo side to accommodate when the following changes are released in httomolib and httomolibgpu (ie, when these changes make their way into the conda packages that httomo installs during CI):
- https://github.com/DiamondLightSource/httomolibgpu/pull/157
- https://github.com/DiamondLightSource/httomolib/pull/17
> Update pipelines to match changes to image saver and rescaler methods

- docs/source/howto/run_httomo.rst
- httomo/cli.py
- tests/test_cli.py
Fixes #458
Also, this change has refactored `cli.py` a bit, separating the different groups of logic into their own functions. Doing that made it easier to test the output directory was being set as expected, and also made the test not need to run a pipeline just to check the setting for the output directory.
> Add CLI flag to pass an existing output directory to httomo (instead of httomo creating one)

- docs/source/_static/css/general.css
- docs/source/conf.py
- docs/source/doc-conda-requirements.yml
> Migrate from `sphinx-panels` to `sphinx-design`

- tests/test_backends/test_httomolibgpu.py
Fixes #510
Note that for the distortion correction memory hook test to pass on CI, this depends on a new release of httomolibgpu being made that contains the changes in https://github.com/DiamondLightSource/httomolibgpu/pull/161.
> Update parameters in distortion correction memory hook test

- docs/source/_templates/autosummary/class.rst
- httomo/transform_loader_params.py
> Update transform loader params API docs

- docs/source/howto/run_httomo.rst
- httomo/cli.py
- httomo/globals.py
- httomo/methods.py
- tests/test_methods.py
Fixes #423 
This PR provides an option to determine `frames_per_chunk` from the saturation bandwidth of the file system in DLS when it is passed as `-1`. It results in more frames per chunk so that the writing performance is increased because less chunks are needed. Several values about raw data chunk cache (rdcc) are modified to optimise the I/O performance of the dataset.
I observed around 60-70% speed-up (depending on the number of MPI ranks) when using `--frames-per-chunk -1` over `--frames-per-chunk 1`. The performance gain of setting rdcc is not as significant as the change in chunk size. Feel free to test this with different datasets, YMMV.
One thing worth to discuss is whether the choice of `--frames-per-chunk -1` means 'decide it automatically' is good or not. Potentially it can …
> Decide the value of frames_per_chunk from saturation bandwidth

- httomo/runner/task_runner.py
Fixes #543
With this simple change, profiling the block splitter script mentioned in #543 now shows the same behaviour as not using the tqdm progress bar iterable at all (ie, the loop being defined as `for block in progress` rather than what it was posted in that issue):
Furthermore, the original pipeline that was run on `ws582` at DLS which previously was getting a RAM OOM error now runs without issue.
> Remove some unnecessary copies during iteration over splitter that's given a file-based dataset source

- docs/source/doc-conda-requirements.yml
For some reason in 8.2.0 `sphinx` version the dependency on `nbsphinx` breaks the build. Until the issue is resolved the solution is to use the older `sphinx` version. The `nbsphinx`  package, however, is required for the build to be successful.
> Fixing docs build

- tests/conftest.py
> Remove unused compressed tomo standard test data

- tests/conftest.py
- tests/test_pipeline_big.py
- tests/test_pipeline_small.py
Pytest has functionality to provide temporary directories for tests (see https://docs.pytest.org/en/stable/how-to/tmp_path.html), so there's no need to have custom logic to setup and teardown temporary directories in tests.
> Simplify temp dir setup/teardown in tests

- docs/source/howto/run_httomo.rst
- httomo/cli.py
- httomo/globals.py
- httomo/method_wrappers/save_intermediate.py
- tests/method_wrappers/test_save_intermediate.py
- tests/test_cli.py
> Add CLI flag for choosing recon filename stem

- .github/workflows/container.yaml
- Dockerfile
> Add container image and release build to ghcr

- httomo/runner/block_split.py
> Separate `BlockSplitter` docstring into sections

- tests/method_wrappers/test_save_intermediate.py
Fixes #577
Based on information in [the hdf5 docs on file locks](https://support.hdfgroup.org/documentation/hdf5/latest/_file_lock.html) saying that the locks are not needed when running multiple processes working together (such as when running processes using MPI), I had noted that running the 6 offending tests in `test_save_intermediate_data` under `mpirun -n 1` never produced the error, and chalked it off as some anomaly where those tests needed to be run under MPI to pass locally.
However, since then, I noticed that those offending tests only ever create the hdf5 file for saving, and the `execute()` method on the wrapper object is never called.
This test is parameterised to have 4 of the 6 failing cases: https://github.com/DiamondLightSource/httomo/blob/c0036b9da10410bc52a4b7fddf8f3c40 …
> Execute intermediate data wrapper in output recon file naming tests

- httomo/method_wrappers/save_intermediate.py
- httomo/methods.py
- httomo/runner/section.py
- httomo/runner/task_runner.py
- tests/method_wrappers/test_save_intermediate.py
- tests/runner/test_section.py
- tests/runner/test_task_runner.py
- tests/test_methods.py
> Use minimum block length as frames-per-chunk value if frames-per-chunk calculation exceeds minimum block length

- tests/test_cli.py
> Expect error status in CLI test with no args passed

- Dockerfile
> Update container image for compatibility with workflows system

- httomo/darks_flats.py
- httomo/method_wrappers/rotation.py
- httomo/transform_loader_params.py
- httomo/yaml_checker.py
1. Making a keyword (`null`) to work for `image_key_path` in the loader by bypassing a check for a valid path (`params[key].strip("/")`) in yaml checker. 
2. Ensuring that the dummy flats/darks are created for data without d/f and the absence of the key
3. Some corrections about the agnostic `normalize_sino` as there was an ambiguity (cupy/numpy) between the `xp` object inside the function and the data passed to that function
> Making a keyword (null) to work for image_key_path in the loader

- httomo/cli.py
- httomo/utils.py
See DLS internal JIRA tickets such as https://jira.diamond.ac.uk/browse/IMGDA-451 and https://jira.diamond.ac.uk/browse/IMGDA-405.
Instead of the program "hanging" in the case when one or more processes get killed but not all of them and the program needs to be Ctrl-c, such as the following:
```
File "/dls/science/users/twi18192/httomo/httomo/runner/section.py", line 185, in determine_minimum_block_length
remainder = chunk_slicing_dim_length % max_slices
remainder = chunk_slicing_dim_length % max_slices
~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
ZeroDivisionError: integer modulo by zero
~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
ZeroDivisionError: integer modulo by zero
^Csrun: interrupt (one more within 1 sec to abort)
srun: StepId=21243475.2 tasks 0-3: running
^Csrun: interrupt (one more within 1 …
```
> Add MPI abort handler for unhandled exceptions

- httomo/cli.py
- tests/test_cli.py
- tests/test_ui_layer.py
> Add httomo version comment to pipeline file copied to output dir
