DiamondLightSource/httomo

src/httomo/misc/corr.py
templates/httomo/httomo.misc.corr/dezinger_filter3d.yaml
templates/httomo/httomo.misc.corr/dezinger_flat_dark_filter3d.yaml
templates/httomo/httomo.misc.corr/median_filter3d.yaml

Adding larix based median and dezinger with templates

httomo correction function with templates

---

src/httomo/recon/rotation.py

Raise a ValueError if `sino_360` is not 2D

---

src/httomo/data/hdf/loaders.py
src/httomo/utils.py

Add colors to the output

---

httomo/task_runner.py
samples/pipeline_template_examples/04_basic_gpu_pipeline_tomo_standard.yaml
samples/pipeline_template_examples/multi_inputs/01_dezing_multi_inputs.yaml
templates/httomolib/httomolib.misc.corr/inpainting_filter3d.yaml
templates/httomolib/httomolib.misc.corr/median_filter3d_cupy.yaml
templates/httomolib/httomolib.misc.corr/remove_outlier3d_cupy.yaml
templates/httomolib/httomolib_modules.yml
wrappers/httomolib/misc.py
wrappers/httomolib/prep.py
wrappers/httomolib/recon.py

redefining the reslicing logic when "all" pattern is involved

New reslicing logic

---

httomo/data/hdf/_utils/save.py
httomo/task_runner.py

See issue #67 for more information on the bug being addressed.

Fix incorrect gathering of data when saving intermediate dataset

---

httomo/_stats/globals.py
httomo/task_runner.py
tests/test_pipeline.py

Also dealt with the problem of potentially passing CuPy arrays into calculation of global statistics

global stats corrections and fix for #64

---

.github/workflows/cpu_tests.yml
httomo/__init__.py
httomo/_stats/globals.py
httomo/cli.py
httomo/data/hdf/_utils/load.py
httomo/data/hdf/_utils/reslice.py
httomo/data/hdf/_utils/save.py
httomo/data/hdf/loaders.py
httomo/data/mpiutil.py
httomo/methods_database/query.py
httomo/task_runner.py
httomo/utils.py
httomo/wrappers_class.py
httomo/yaml_checker.py
httomo/yaml_utils.py
pyproject.toml
samples/pipeline_template_examples/DLS/03_i12_separate_darks_flats.yaml
samples/pipeline_template_examples/testing/sweep_testing_pipeline.yaml
templates/tomopy/remove_unsupported_templates.py
templates/yaml_templates_generator.py
tests/conftest.py
tests/test_cli.py
tests/test_loader.py
tests/test_mpiutil.py
tests/test_pipeline.py
tests/test_reslice.py
tests/test_yaml_checker.py

Refactor the task runner

---

httomo/cli.py
tests/conftest.py

Change `save_all` to `save-all` to make it consistent with other flags

---

.scripts/conda_upload.sh

Added the passphrase and scripts, so it should fix  #163

adding scripts for conda upload

---

README.rst

DOC: add instructions to use mamba

---

.github/workflows/doc_conda.yml
docs/source/conf.py
docs/source/tutorials/yaml.rst
docs/source/yaml_doc_generator.py

- Add links to functions in httomolib
- Add download link for yaml templates

Add links to httomolib

---

httomo/runner/auxiliary_data.py
httomo/runner/dataset.py
httomo/utils.py
tests/runner/test_dataset_block.py

This is the first step towards a more robust and independent way to generate and work with `DataSetBlock`.

Refactored DataSetBlock to be standalone and more robust

---

conda/environment.yml
httomo/cli.py
httomo/data/dataset_store.py
httomo/data/hdf/_utils/load.py
httomo/data/hdf/_utils/reslice.py
httomo/data/hdf/_utils/save.py
httomo/data/hdf/loaders.py
httomo/globals.py
httomo/loaders/standard_tomo_loader.py
httomo/logger.py
httomo/method_wrappers/generic.py
httomo/method_wrappers/rotation.py
httomo/method_wrappers/stats_calc.py
httomo/runner/section.py
httomo/runner/task_runner.py
httomo/utils.py
tests/test_pipeline.py

Main changes:
- Switch from `logging` to `loguru` for logger object
- Fixes #172
- Fixes #188
- Fixes #235
- Fixes #261
- Fixes #288
- Fixes #290
- Fixes #291
- Fixes #292

Various logging improvements

---

docs/source/yaml_doc_generator.py

Fix failing CI docs build

---

.github/workflows/cpu_tests.yml
conda/environment-cpu.yml
httomo/globals.py
httomo/runner/task_runner.py
tests/runner/test_task_runner.py

fixing the issue of `MAX_CPU_SLICES` not enabled for the all-cpu section.

fix for cpu max memory estimation

---

httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/recon/algorithm.py
tests/test_backends/test_httomolibgpu.py

FBP memory estimation corrections

---

conda/environment-cpu.yml
docs/source/howto/installation.rst
httomo/runner/auxiliary_data.py

fixes cpu-only environment and also auxilary data condition for cupy

---

conda/environment.yml
docs/source/backends/templates.rst
docs/source/doc-conda-requirements.yml
httomo/methods_database/packages/external/httomolibgpu/httomolibgpu.yaml
tests/samples/pipeline_template_examples/pipeline_360deg_gpu2.yaml
tests/test_pipeline.py

resampler library info fixes

---

tests/sweep_runner/test_param_sweep_runner.py

Fix failing sweep runner image wrapper MPI test

---

httomo/method_wrappers/rotation.py
tests/method_wrappers/test_rotation.py

Enable rotation wrapper to work with padded blocks

---

.github/workflows/httomo_version_tag.yml
.github/workflows/run_tests_iris.yml
conda/environment.yml
conda/recipe/meta.yaml

fixing conda build upload

---

.github/workflows/httomo_pypi_publish.yml
README.rst

fixing the pypi path

---

docs/source/doc-conda-requirements.yml

Add python version <3.13 constraint in docs env

---

docs/source/howto/run_httomo.rst
httomo/cli.py
tests/test_cli.py

Remove `--output-folder-path` CLI flag

---

docs/source/conf.py
docs/source/howto/process_lists/process_list_configure.rst
docs/source/howto/run_httomo.rst
docs/source/pipelines/yaml.rst
docs/sphinx-build.sh

Fixes #479 
Fixes #496 
Fixes #480 
Fixes #491 
Fixes #485 
Fixes #481 
Fixes #489

Various small docs fixes

---

httomo/loaders/standard_tomo_loader.py
tests/loaders/test_standard_tomo_loader.py
tests/test_pipeline.py

adding extraction of angles related to data indices only

---

httomo/method_wrappers/__init__.py
httomo/method_wrappers/distortion_correction.py
httomo/method_wrappers/generic.py
httomo/transform_layer.py
httomo/ui_layer.py
tests/method_wrappers/test_data_reducer.py
tests/method_wrappers/test_dezinging.py
tests/method_wrappers/test_distortion_correction.py
tests/method_wrappers/test_generic.py
tests/method_wrappers/test_images.py
tests/method_wrappers/test_make_method_wrapper.py
tests/method_wrappers/test_reconstruction.py
tests/method_wrappers/test_rotation.py
tests/method_wrappers/test_save_intermediate.py
tests/method_wrappers/test_stats_calc.py
tests/runner/test_task_runner.py
tests/sweep_runner/test_param_sweep_runner.py
tests/testing_utils.py

Fixes #38 (also see #455 for other relevant details)

Add distortion correction wrapper

---

httomo/runner/section.py

Add and update docstrings in `section.py` module

---

httomo/darks_flats.py

Add docstrings for `darks_flats.py` module and members

---

httomo/cli_utils.py
httomo/ui_layer.py
tests/test_ui_layer.py

Remove pipeline file extension check

---

docs/source/pipelines/yaml.rst
tests/samples/pipeline_template_examples/DLS/01_diad_pipeline_gpu.yaml
tests/samples/pipeline_template_examples/parameter-sweep-cor.yaml
tests/samples/pipeline_template_examples/parameter-sweep-paganin.yaml
tests/samples/pipeline_template_examples/pipeline_360deg_gpu2.yaml
tests/samples/pipeline_template_examples/pipeline_360deg_iterative_gpu3.yaml
tests/samples/pipeline_template_examples/pipeline_cpu3.yaml
tests/test_pipeline.py

Adding inline comments to some full pipelines

adding inline comments for some pipelines

---

docs/source/reference/loaders.rst
httomo/loaders/types.py
httomo/transform_loader_params.py
httomo/ui_layer.py
tests/test_transform_loader_params.py

Enable automatic discovery of NXtomo entry in input data

---

httomo/runner/block_split.py

Remove unused logger object

---

docs/source/reference/loaders.rst
docs/source/utilities/yaml_checker.rst
httomo/yaml_checker.py
tests/samples/pipeline_template_examples/testing/loader_with_all_auto_params.yaml
tests/samples/pipeline_template_examples/testing/loader_with_some_auto_params.yaml
tests/test_yaml_checker.py

Add loader `auto` parameter value support to YAML checker

---

tests/test_ui_layer.py

Add missing type hints to UI layer tests

---

httomo/sweep_runner/param_sweep_runner.py
tests/sweep_runner/test_param_sweep_runner.py

Fixes the issue with sweep runs getting an error when trying to save the output of a method to an hdf5 file using the intermediate data wrapper
```
(base) root@57b6bd69e7ba:/httomo# python -m httomo run tests/test_data/tomo_standard.nxs docs/source/pipelines_full/gpu_pipeline_sweep_FBP.yaml output_dir/
See the full log file at: output_dir/19-05-2025_14_06_57_output/user.log
Loading data with shape (180, 4, 160)
Running data_reducer (httomolib)
Running normalize (httomolibgpu)
Running FBP3d_tomobar (httomolibgpu)
Beginning parameter sweep
Parameter name: center
Total number of values across all processes: 8
Values executed in this process: 8
0%|          | 0/8 [00:00<?, ?value/s, center=1100]
12%|#2        | 1/8 [00:00<00:01,  5.74value/s, center=1125]
25%|##5       | 2/8 [00:00<00:00, …
```

Fix sweep runner not passing minimum block length to intermediate data wrapper

---

httomo/transform_layer.py
tests/test_parallel_pipeline_big.py
tests/test_pipeline_big.py

Cherry-picks last commit in #613, see OP in that PR for info on the change.

Don't insert intermediate file saving method in sweep run
